### PR TITLE
Update quotes.json

### PR DESCRIPTION
**Pull request by hongjinn**
I'd like to add my favorite quote from Cleanthes:
Lead me, O Zeus, and thou O Destiny,
The way that I am bid by you to go:
To follow I am ready. If I choose not,
I make myself a wretch, and still must follow.

### CODE REVIEW

**Comment by benhoneywill** [comment]
Thank you for your contribution @hongjinn!

I will merge this right away 👍

**Comment by hongjinn** [comment]
Great work! =)

**Comment by shadoath** [comment]
@hongjinn what does this quote mean to you? How do you see it in a stoic way?

**Comment by hongjinn** [comment]
@shadoath My 2 cents... let's say a meteor blew up my car. That's pretty unlucky and I could complain bitterly about it. But my car is still busted whether I accept it or not. The only thing I can control is my response to it. 

Like Marcus says "Nature gives and nature takes away. Anyone with sense and humility will tell her, "Give and take as you please," not out of defiance, but out of obedience and goodwill."

Also when lucky things happen to me I usually don't question it and take it for granted.

**Pull request merged**
